---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.14.4
      helm:
        releaseName: cert-manager
        valuesObject:
          installCRDs: true
    - repoURL: git@github.com:timmhirsens/gitops-demo-infra-team.git
      targetRevision: HEAD
      path: manifests/cert-manager
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
