---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    helm:
      releaseName: ingress-nginx
      valuesObject:
        controller:
          publishService:
            enable: true
          service:
            annotations:
              kubernetes.digitalocean.com/load-balancer-id: "haeger-demo-lb-nginx"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx

  syncPolicy:
      syncOptions:
      - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

