---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa-gatekeeper-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:timmhirsens/gitops-demo-team-infra.git
    targetRevision: HEAD
    path: manifests/opa-gatekeeper-config

  destination:
    server: "https://kubernetes.default.svc"
    namespace: gatekeeper-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
