---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 58.5.1
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring

  syncPolicy:
      syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true

